name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # - name: Run health test
      #   run: npm run test:health

      - name: Build Docker image
        run: docker build -t therealayinla/minilink-api .

      # - name: Push Docker image
      #   run: docker push therealayinla/minilink-api

      - name: Run container
        run: |
          docker run -d \
            -p 3000:3000 \
            -e NODE_ENV=development \
            -e API_VERSION=1.0.0 \
            -e DEFAULT_PORT=3000 \
            -e DB_URI="postgresql://fake:fake@localhost:5432/fake" \
            --name minilink-health-test \
            therealayinla/minilink-api
          sleep 5

      - name: Health check
        run: |
          curl --fail http://localhost:3000/health

      - name: Check container logs 2
        if: always()
        run: docker logs minilink-health-test

      - name: Stop container
        if: always()
        run: |
          docker stop minilink-health-test
          docker rm -f minilink-health-test
