name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: install dependencies
        run: npm CI

      # - name: Run health test
      #   run: npm run test:health

      - name: Build Docker image
        run: docker build -t therealayinla/minilink-api .

      # - name: Push Docker image
      #   run: docker push therealayinla/minilink-api

      - name: Run container
        run: |
          docker run -d -p 3000:3000 --name minilink-health-test therealayinla/minilink-api
          sleep 5

      - name: Health check
        run: |
          curl --fail http://localhost:3000/health

      - name: Stop container
        if: always()
        run: |
          docker stop minilink-health-test
          docker rm -f minilink-health-test
